# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      CONFIGURATION: release
      VERSION: ${{ github.event.release.tag_name }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack
        run: dotnet pack --no-build --no-restore -o ./out
      - name: Add NuGet source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github
      - name: Push NuGet package
        run: dotnet nuget push ./out/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}
      - name: Push NuGet package to NuGet.org
        run: dotnet nuget push ./out/*.nupkg --source nuget.org --api-key ${{ secrets.NUGET_API_KEY }}
