# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release
run-name: ${{ github.event.release.name }}

on:
  release:
    types: [published]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  CONFIGURATION: release
  VERSION: ${{ github.event.release.tag_name }}

permissions:
  contents: read
  packages: write

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack
        run: dotnet pack --no-build --no-restore -o ./out
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: ./out
          if-no-files-found: error
          retention-days: 5
  
  publish_github:
    needs: [ pack ]
    runs-on: ubuntu-latest

    env:
      NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/setup-dotnet@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ./out
      - name: Push NuGet package
        run: dotnet nuget push ./out/*.nupkg --source ${{ env.NUGET_SOURCE }} --api-key ${{ env.NUGET_API_KEY }}

  publish_nuget:
    if: '!github.event.release.prerelease'
    needs: [ pack ]
    runs-on: ubuntu-latest
    
    env:
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    
    steps:
      - uses: actions/setup-dotnet@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ./out
      - name: Push NuGet package to NuGet.org
        run: dotnet nuget push ./out/*.nupkg --source ${{ env.NUGET_SOURCE }} --api-key ${{ env.NUGET_API_KEY }}
